services:
  - type: web
    name: PopularFrontArchive
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn PopularFrontArchive.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true